@echo off
chcp 65001 >nul
echo.
echo ====================================
echo   Configurar Android SDK
echo ====================================
echo.

:: Caminhos comuns do Android SDK no Windows
set "SDK1=%USERPROFILE%\AppData\Local\Android\Sdk"
set "SDK2=C:\Android\Sdk"
set "SDK3=C:\Users\%USERNAME%\Android\Sdk"
set "SDK4=%LOCALAPPDATA%\Android\Sdk"
set "SDK5=%ANDROID_HOME%"

set "SDK_PATH="

echo Procurando Android SDK nos caminhos comuns...
echo.

:: Verifica ANDROID_HOME primeiro
if defined ANDROID_HOME (
    echo [Verificando] ANDROID_HOME: %ANDROID_HOME%
    if exist "%ANDROID_HOME%\platform-tools\adb.exe" (
        set "SDK_PATH=%ANDROID_HOME%"
        echo ✓ Android SDK ENCONTRADO via ANDROID_HOME
        echo.
        goto :found
    ) else (
        echo   ✗ ANDROID_HOME existe mas não tem platform-tools
        echo.
    )
)

:: Verifica caminhos comuns
echo [Verificando] %SDK1%
if exist "%SDK1%\platform-tools\adb.exe" (
    set "SDK_PATH=%SDK1%"
    echo ✓ Android SDK ENCONTRADO
    echo.
    goto :found
) else (
    echo   ✗ Não encontrado
)

echo [Verificando] %SDK4%
if exist "%SDK4%\platform-tools\adb.exe" (
    set "SDK_PATH=%SDK4%"
    echo ✓ Android SDK ENCONTRADO
    echo.
    goto :found
) else (
    echo   ✗ Não encontrado
)

echo [Verificando] %SDK2%
if exist "%SDK2%\platform-tools\adb.exe" (
    set "SDK_PATH=%SDK2%"
    echo ✓ Android SDK ENCONTRADO
    echo.
    goto :found
) else (
    echo   ✗ Não encontrado
)

echo [Verificando] %SDK3%
if exist "%SDK3%\platform-tools\adb.exe" (
    set "SDK_PATH=%SDK3%"
    echo ✓ Android SDK ENCONTRADO
    echo.
    goto :found
) else (
    echo   ✗ Não encontrado
)

:: SDK não encontrado
echo.
echo ================================================
echo ❌ Android SDK NÃO ENCONTRADO automaticamente!
echo ================================================
echo.
echo OPÇÕES:
echo.
echo 1. INSTALAR Android Studio:
echo    → https://developer.android.com/studio
echo    → Na instalação, marque "Android SDK"
echo    → Execute este script novamente
echo.
echo 2. INFORMAR caminho manualmente:
echo    → Encontre onde está o Android SDK
echo    → Digite o caminho completo abaixo
echo.
echo ================================================
echo.
set /p "SDK_PATH=Digite o caminho completo do Android SDK (ou deixe vazio para sair): "

if "%SDK_PATH%"=="" (
    echo.
    echo ❌ Operação cancelada.
    echo.
    pause
    exit /b 1
)

:: Remove aspas se o usuário colou com aspas
set "SDK_PATH=%SDK_PATH:"=%"

:: Valida o caminho informado
if not exist "%SDK_PATH%\platform-tools\adb.exe" (
    echo.
    echo ================================================
    echo ❌ ERRO: Caminho inválido!
    echo ================================================
    echo.
    echo O caminho informado não contém um Android SDK válido.
    echo.
    echo Esperado encontrar: %SDK_PATH%\platform-tools\adb.exe
    echo.
    echo Certifique-se de que:
    echo   1. O caminho está correto
    echo   2. O Android SDK está instalado
    echo   3. A pasta platform-tools existe
    echo.
    pause
    exit /b 1
)

:found
echo ================================================
echo ✅ Android SDK Válido Encontrado!
echo ================================================
echo.
echo Caminho: %SDK_PATH%
echo.

:: Verifica componentes importantes
echo Verificando componentes:
if exist "%SDK_PATH%\platform-tools\adb.exe" (
    echo   ✓ platform-tools [OK]
) else (
    echo   ✗ platform-tools [FALTANDO]
)

if exist "%SDK_PATH%\platforms" (
    echo   ✓ platforms [OK]
) else (
    echo   ✗ platforms [FALTANDO]
)

if exist "%SDK_PATH%\build-tools" (
    echo   ✓ build-tools [OK]
) else (
    echo   ✗ build-tools [FALTANDO]
)

echo.

:: Converte o caminho para formato Java (barras duplas)
set "SDK_JAVA=%SDK_PATH:\=\\%"

:: Cria o arquivo local.properties
echo ## This file was auto-generated by criar-local-properties.bat > local.properties
echo ## Android SDK location >> local.properties
echo. >> local.properties
echo sdk.dir=%SDK_JAVA% >> local.properties

echo ================================================
echo ✅ Arquivo local.properties CRIADO!
echo ================================================
echo.
echo Conteúdo:
echo -----------------------------------
type local.properties
echo -----------------------------------
echo.
echo ✅ Configuração completa!
echo.
echo PRÓXIMO PASSO:
echo    .\gradlew.bat assembleDebug
echo.
pause
