@echo off
chcp 65001 >nul
echo.
echo ====================================
echo   Criando local.properties
echo ====================================
echo.

:: Caminhos comuns do Android SDK no Windows
set "SDK1=%USERPROFILE%\AppData\Local\Android\Sdk"
set "SDK2=C:\Android\Sdk"
set "SDK3=C:\Users\%USERNAME%\Android\Sdk"
set "SDK4=%ANDROID_HOME%"

set "SDK_PATH="

:: Verifica ANDROID_HOME primeiro
if defined ANDROID_HOME (
    if exist "%ANDROID_HOME%\platform-tools" (
        set "SDK_PATH=%ANDROID_HOME%"
        echo ✓ Android SDK encontrado via ANDROID_HOME
        goto :found
    )
)

:: Verifica caminhos comuns
if exist "%SDK1%\platform-tools" (
    set "SDK_PATH=%SDK1%"
    echo ✓ Android SDK encontrado em: %SDK1%
    goto :found
)

if exist "%SDK2%\platform-tools" (
    set "SDK_PATH=%SDK2%"
    echo ✓ Android SDK encontrado em: %SDK2%
    goto :found
)

if exist "%SDK3%\platform-tools" (
    set "SDK_PATH=%SDK3%"
    echo ✓ Android SDK encontrado em: %SDK3%
    goto :found
)

:: SDK não encontrado
echo.
echo ❌ Android SDK NÃO encontrado nos caminhos comuns!
echo.
echo Caminhos verificados:
echo   - %SDK1%
echo   - %SDK2%
echo   - %SDK3%
echo.
echo INSTRUÇÕES:
echo 1. Instale Android Studio: https://developer.android.com/studio
echo 2. Ou informe o caminho manualmente abaixo
echo.
set /p "SDK_PATH=Digite o caminho completo do Android SDK: "

if not exist "%SDK_PATH%\platform-tools" (
    echo.
    echo ❌ Caminho inválido! Não encontrei platform-tools nesse local.
    echo.
    pause
    exit /b 1
)

:found
:: Converte o caminho para formato Java (barras duplas)
set "SDK_JAVA=%SDK_PATH:\=\\%"

:: Cria o arquivo local.properties
echo ## This file was auto-generated by criar-local-properties.bat > local.properties
echo ## Location of the Android SDK >> local.properties
echo. >> local.properties
echo sdk.dir=%SDK_JAVA% >> local.properties

echo.
echo ✅ Arquivo local.properties criado com sucesso!
echo.
echo Conteúdo:
echo -----------------------------------
type local.properties
echo -----------------------------------
echo.
echo ✅ Agora você pode compilar com:
echo    .\gradlew.bat assembleDebug
echo.
pause
